### PR TITLE
feat: add `apt` auto detection for macOS and iOS

### PR DESCRIPTION
**Pull request by Absolucy**
See: https://github.com/ProcursusTeam/Procursus

### CODE REVIEW

**Comment by rami3l** [comment]
Thanks for your contribution!

I'd say sorry for not catching up with the context: I do know that `apt` is used on jailbroken iPhones, but I don't know `apt` is also used on Macs. Would you mind telling me what it's for, so that I can better evaluate the necessity of this change? 

PS: The part that you have modified only affects auto detection of package managers: I believe that currently specifying `--using=apt` should always work. If this is not the case, please don't hesitate to inform me. :)

**Comment by Absolucy** [comment]
It's used on jailbroken iPhones, but it's also been ported to macOS, as [kind of a homebrew/macOS alternative](https://github.com/ProcursusTeam/Procursus), fully functional and such. I use it on my M1 Air, without Homebrew or MacPortsinstalled at all.

**Review by rami3l — APPROVED** [review]

**Comment by rami3l** [comment]
@Absolucy Got it.

Before merging this change, however, maybe it's better to update my test suite to ensure it's working alright (at least on macOS). I'm glad to help you with that, but could you please let me know how did you install `apt`, so that I can reuse my previously established test for macOS CI?

Thanks a lot!

**Comment by Absolucy** [comment]
unpack this .tar.zst into / (I think it was `tar --preserve-permissions -C /` or something?) to bootstrap Procursus: https://apt.procurs.us/bootstrap_darwin-amd64.tar.zst

it's been a while so I don't really remember properly

**Comment by rami3l** [comment]
@Absolucy Weird enough, `apt` seems to conflict with something inside JDK 😂

Hold on, it might take me a little while to figure this out...

**Comment by Absolucy** [comment]
@rami3l i think that happens if it's not in PATH properly? `/opt/procursus/bin` needs to be at the front of PATH

**Comment by rami3l** [comment]
@Absolucy Yeah, thanks for the hint. Please be patient :)

**Comment by rami3l** [comment]
@Absolucy Finally I decided to lower the priority of `apt` on `macOS` due to possible name collision (those who didn't install `apt` but did install a JDK will suffer from a high priority thereof).

Since you don't use `brew` or `port` at the moment, this won't be a problem for you. However, if needed, you can always override the default by running `echo 'default_pm = "apt"' >> $HOME/.config/pacaptr/pacaptr.toml` :)

**Pull request merged**
